## Setting for server
server:
  port: 8081
  servlet:
    context-path: /ak2
## Setting for DB
spring:
  jpa:
    hibernate:
      ddl-auto: none
      show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        boot:
          allow_jdbc_metadata_access: false
  data:
    redis:
      repositories:
        enabled: false
      cluster:
        nodes:
          - 127.0.0.1:7001
          - 127.0.0.1:7002
          - 127.0.0.1:7003
          - 127.0.0.1:7004
          - 127.0.0.1:7005
          - 127.0.0.1:7006
    lettuce:
      cluster:
        refresh:
          adaptive: true
          period: 30s
  session:
    store-type: redis
    redis:
      flush-mode: on-save
#      namespace: ak2-session
  datasource:
    url: jdbc:postgresql://127.0.0.1:13306/ak2
    username: docker
    password: docker
    continue-on-error: true
## Logging
logging:
  level:
    org:
      springframework:
        security: DEBUG
## Management
management:
  metrics:
    enable: false